inherit_from: .rubocop_todo.yml

require: 
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec # or rubocop-minitest

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/GuardClause:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: False

RSpec/EmptyExampleGroup:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
   Enabled: False
# https://stackoverflow.com/questions/64502435/layout-endofline-carriage-return-character-detected-module-tieconnector

LexicallyScopedActionFilter:
  Enabled: False
# Momentaneamente se deshabilita porque solo interfiere con la convención de Rails, no nuestro código
